version: '3'
services:
    app:
        entrypoint: "/docker-entry.sh"
        build:
            context: ./
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        hostname: bss-tracker
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        links:
          - "db"
        depends_on:
          db:
            condition: service_healthy
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: true
            MYSQL_DATABASE: bss_tracker
            MYSQL_USER: bss_tracker
            MYSQL_PASSWORD: "bss_tracker"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        ports:
            - "3306:3306"
